# Generated by Django 3.1.3 on 2020-12-01 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
