# Generated by Django 3.1.3 on 2020-12-02 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0002_twitteruser_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='follow',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
